# user and repo
user        := `whoami`
current_dir := `basename $( pwd )`

# Colors
RED     := "\\u001b[31m"
GREEN   := "\\u001b[32m"
RESET   := "\\u001b[0m"

_default:
    @echo "\nHi {{GREEN}}{{user}}!{{RESET}} Welcome to {{RED}}{{current_dir}}{{RESET}}\n"

    @just --list --unsorted

# setup python virtual env, activate and install requirements
setup:
    python -m venv .venv
    source .venv/bin/activate
    pip install -r requirements.txt
    @echo "run following to activate environment"
    @echo "\n\t{{GREEN}}source .venv/bin/activate{{RESET}}"

# run pytest
test:
    pytest -vvv

# run flake8 linter
lint:
    flake8 --exclude .venv

# run full build, lint and test
build: lint test

# run server
demo-server:
    flask run --debug

# run JS server
demo-js-server:
    cd demo-world-app-js && \
        npm install && \
        npm run dev

# run demo against running server
demo:
    curl "http://127.0.0.1:5000" \
        -H 'Content-Type: application/json' \
        --data '{"x":0, "y":0, "direction": "N", \
            "commands": ["f", "f", "f", "f","r", "r"] \
        }'

# clean virtual env and cache
clean:
    # deactivate
    rm -rf __pycache__ pytest-env
